# -*- coding: utf-8 -*-
"""counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17A5urR0umCN6Vl1x7_lNZxSel-u3bvuB
"""

grades = input().split()

failedPeople = 0
for i in grades:
  if(int(i)<60):failedPeople+=1
print(failedPeople)